# Generated by Django 3.2.9 on 2021-11-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('comprador', models.CharField(max_length=100, verbose_name='Comprador')),
                ('metodo_de_pagamento', models.CharField(choices=[('cartao', 'Cartão'), ('a_prazo', 'A Prazo'), ('a_vista', 'À Vista')], max_length=20, verbose_name='Método de Pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago?')),
                ('loja', models.CharField(max_length=100, verbose_name='Loja')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_de_pagamento', models.DateField(verbose_name='Data de Pagamento')),
                ('parcelas', models.PositiveIntegerField(default=1, verbose_name='Parcelas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Numero da Parcela')),
                ('data_de_pagamento', models.DateField(verbose_name='Data de Pagamento')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.conta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
