# Generated by Django 3.2.9 on 2021-11-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='produto',
            field=models.CharField(default='foo', max_length=100, verbose_name='Produto'),
            preserve_default=False,
        ),
    ]
